CREATE DATABASE mikrotik;
USE mikrotik;
CREATE TABLE community(id INTEGER NOT NULL KEY AUTO_INCREMENT, name VARCHAR(255) NOT_NULL);
CREATE TABLE router(id INTEGER NOT NULL KEY AUTO_INCREMENT, name VARCHAR(255) NOT_NULL,ip UNSIGNED INTEGER NOT_NULL, community VARCHAR(255) NOT NULL);